receivers:
  githubactions:
    secret: ${env:WEBHOOK_SECRET}
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  pprof:
  zpages:
    endpoint: "localhost:55679"

exporters:
  debug:
    verbosity: basic
  otlp/apm:
    endpoint: "${env:APM_SERVER_URL}"
    headers:
      Authorization: "Bearer ${env:APM_SERVER_BEARER_TOKEN}"
    sending_queue:
      enabled: false

service:
  extensions: [zpages, pprof]
  pipelines:
    traces:
      receivers: [githubactions]
      processors: [batch]
      exporters: [debug, otlp/apm]
