receivers:
  githubactions:
    secret: ${env:WEBHOOK_SECRET}
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  pprof:
  zpages:
    endpoint: "localhost:55679"

exporters:
  debug:
    verbosity: basic

service:
  extensions: [zpages, pprof]
  pipelines:
    traces:
      receivers: [githubactions]
      processors: [batch]
      exporters: [debug]
